name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    environment: test_deployment
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: gw
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      #      - uses: actions-rs/toolchain@v1
      #        with:
      #          toolchain: nightly-2022-02-09
      #          components: rustfmt
      #          override: true
      - name: Install build dependencies
        run: sudo apt update -qq && sudo apt install -y -qq libudev-dev

      - name: Cache rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"

      - name: Run user server
        run: |
          cargo build --bin user
          cargo run --bin user &

      - name: Run tests
        run: cargo test
